name: Publish Version


on:
  release:
    branches:
      - main
    types: [edited]


jobs:
  build-and-publish:
    name: Build and Publish on PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Clean build artifacts
        run: rm -rf build dist *.egg-info

      - name: Install build
        run: python -m pip install --upgrade build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: True
